# Generated by Django 4.2.5 on 2023-09-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subTitle",
                    models.CharField(
                        help_text="Малый заголовок, в дефолтной версии Let me Explain it!",
                        max_length=100,
                        verbose_name="Малый заголовок",
                    ),
                ),
                (
                    "mainTitle",
                    models.CharField(
                        help_text="Основной заголовок, в дефолтной версии Курсы по подготовке к USMLE",
                        max_length=100,
                        verbose_name="Основной заголовок",
                    ),
                ),
                (
                    "buttonOne",
                    models.CharField(
                        help_text="Текст на белой кнопке, по дефлоту Узнать по больше",
                        max_length=100,
                        verbose_name="Белая кнопка",
                    ),
                ),
                (
                    "buttonTwo",
                    models.CharField(
                        help_text="Текст на синей кнопке, по дефолту Записаться на курсы",
                        max_length=100,
                        verbose_name="Синия кнопка",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
