# Generated by Django 4.2.5 on 2023-09-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="header",
            options={"verbose_name": "Хедер", "verbose_name_plural": "Хедеры"},
        ),
        migrations.AlterField(
            model_name="header",
            name="buttonOne",
            field=models.CharField(
                default="Узнать по больше",
                help_text="Текст на белой кнопке, по дефлоту Узнать по больше",
                max_length=100,
                verbose_name="Белая кнопка",
            ),
        ),
        migrations.AlterField(
            model_name="header",
            name="buttonTwo",
            field=models.CharField(
                default="Записаться на курсы",
                help_text="Текст на синей кнопке, по дефолту Записаться на курсы",
                max_length=100,
                verbose_name="Синия кнопка",
            ),
        ),
        migrations.AlterField(
            model_name="header",
            name="mainTitle",
            field=models.CharField(
                default="Курсы по подготовке к USMLE",
                help_text="Основной заголовок, в дефолтной версии Курсы по подготовке к USMLE",
                max_length=100,
                verbose_name="Основной заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="header",
            name="subTitle",
            field=models.CharField(
                default="Let me Explain it",
                help_text="Малый заголовок, в дефолтной версии Let me Explain it!",
                max_length=100,
                verbose_name="Малый заголовок",
            ),
        ),
    ]
