# Generated by Django 4.2.5 on 2023-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_alter_header_options_alter_header_buttonone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstThreeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titleOne",
                    models.CharField(
                        default="Команда Менторов",
                        help_text="Заголовок первой карточки, по дефолту Команда Менторов",
                        max_length=50,
                        verbose_name="Заголовок карточки 1",
                    ),
                ),
                (
                    "titleTwo",
                    models.CharField(
                        default="Общество развития Медиков",
                        help_text="Заголовок второй карточки, по дефолту Общество развития Медиков",
                        max_length=50,
                        verbose_name="Заголовок карточки 2",
                    ),
                ),
                (
                    "titleThree",
                    models.CharField(
                        default="Поднимите себя до мирового стандарта",
                        help_text="Заголовок терий карточки, по дефолту Поднимите себя до мирового стандарта",
                        max_length=50,
                        verbose_name="Заголовок карточки 3",
                    ),
                ),
                (
                    "descriptionOne",
                    models.TextField(
                        default="Успешно сдавшие USMLE преподаватели, практикующие резиденты США обучат и покажут вам дорогу",
                        help_text="Добавтье описание к первой карточке",
                        max_length=300,
                        verbose_name="Описание первой карточки",
                    ),
                ),
                (
                    "descriptionTwo",
                    models.TextField(
                        default="Познакомитесь с кругом новых единомышленников, в тяжелом обучении всегда легче с другом, от первокурсников до опытных врачей",
                        help_text="Добавтье описание ко второй карточке",
                        max_length=300,
                        verbose_name="Описание второй карточки",
                    ),
                ),
                (
                    "descriptionThree",
                    models.TextField(
                        default="Готовьтесь к самому сложному экзамену по медицине в мире чтобы соответствовать высшему уровню профессионализма",
                        help_text="Добавтье описание к третей карточке",
                        max_length=300,
                        verbose_name="Описание третей карточки",
                    ),
                ),
                (
                    "buttonOne",
                    models.CharField(
                        default="Read more",
                        help_text="Текст на кнопке под перой карточкой",
                        max_length=50,
                        verbose_name="Кнопка номер 1 под карточкой",
                    ),
                ),
                (
                    "buttonTwo",
                    models.CharField(
                        default="Read more",
                        help_text="Текст на кнопке под второй карточкой",
                        max_length=50,
                        verbose_name="Кнопка номер 2 под карточкой",
                    ),
                ),
                (
                    "buttonThree",
                    models.CharField(
                        default="Read more",
                        help_text="Текст на кнопке под третей карточкой",
                        max_length=50,
                        verbose_name="Кнопка номер 3 под карточкой",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Первые 3 карточки",
                "verbose_name_plural": "Первые 3 карточки",
            },
        ),
    ]
