# Generated by Django 4.2.5 on 2023-09-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0003_firstthreecard"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondThreeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Заголовок",
                        max_length=50,
                        verbose_name="Заголовок карточки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Описание",
                        max_length=300,
                        verbose_name="Описание карточки",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Read more",
                        max_length=50,
                        verbose_name="Текст на кнопке",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Вторая карточка в певром блоке",
                "verbose_name_plural": "Вторая карточка",
            },
        ),
        migrations.CreateModel(
            name="ThirdThreeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Заголовок",
                        max_length=50,
                        verbose_name="Заголовок карточки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Описание",
                        max_length=300,
                        verbose_name="Описание карточки",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Read more",
                        max_length=50,
                        verbose_name="Текст на кнопке",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Третья карточка в певром блоке",
                "verbose_name_plural": "Третья карточка",
            },
        ),
        migrations.AlterModelOptions(
            name="firstthreecard",
            options={
                "verbose_name": "Первая карточка в певром блоке",
                "verbose_name_plural": "Перавая карточка",
            },
        ),
        migrations.RemoveField(
            model_name="firstthreecard",
            name="buttonOne",
        ),
        migrations.RemoveField(
            model_name="firstthreecard",
            name="buttonThree",
        ),
        migrations.RemoveField(
            model_name="firstthreecard",
            name="buttonTwo",
        ),
        migrations.RemoveField(
            model_name="firstthreecard",
            name="descriptionOne",
        ),
        migrations.RemoveField(
            model_name="firstthreecard",
            name="descriptionThree",
        ),
        migrations.RemoveField(
            model_name="firstthreecard",
            name="descriptionTwo",
        ),
        migrations.RemoveField(
            model_name="firstthreecard",
            name="titleOne",
        ),
        migrations.RemoveField(
            model_name="firstthreecard",
            name="titleThree",
        ),
        migrations.RemoveField(
            model_name="firstthreecard",
            name="titleTwo",
        ),
        migrations.AddField(
            model_name="firstthreecard",
            name="button_text",
            field=models.CharField(
                default="Read more", max_length=50, verbose_name="Текст на кнопке"
            ),
        ),
        migrations.AddField(
            model_name="firstthreecard",
            name="description",
            field=models.TextField(
                default="Описание", max_length=300, verbose_name="Описание карточки"
            ),
        ),
        migrations.AddField(
            model_name="firstthreecard",
            name="title",
            field=models.CharField(
                default="Заголовок", max_length=50, verbose_name="Заголовок карточки"
            ),
        ),
    ]
