# Generated by Django 4.2.5 on 2023-09-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0004_secondthreecard_thirdthreecard_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstTopCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Команда Менторов",
                        help_text="Заголовок первой карточки, по дефолту Команда Менторов",
                        max_length=50,
                        verbose_name="Заголовок карточки 1",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Успешно сдавшие USMLE преподаватели, практикующие резиденты США обучат и покажут вам дорогу",
                        help_text="Добавтье описание к первой карточке",
                        max_length=300,
                        verbose_name="Описание первой карточки",
                    ),
                ),
                (
                    "button",
                    models.CharField(
                        default="Read more",
                        help_text="Текст на кнопке под перой карточкой",
                        max_length=50,
                        verbose_name="Кнопка номер 1 под карточкой",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Первая карточка топ блока",
                "verbose_name_plural": "Первая карточка топ блока",
            },
        ),
        migrations.DeleteModel(
            name="FirstThreeCard",
        ),
        migrations.DeleteModel(
            name="SecondThreeCard",
        ),
        migrations.DeleteModel(
            name="ThirdThreeCard",
        ),
    ]
