# Generated by Django 4.2.5 on 2023-09-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0005_firsttopcard_delete_firstthreecard_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondTopCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Общество развития Медиков",
                        help_text="Заголовок второй карточки, по дефолту Общество развития Медиков",
                        max_length=50,
                        verbose_name="Заголовок карточки 2",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Познакомитесь с кругом новых единомышленников, в тяжелом обучении всегда легче с другом, от первокурсников до опытных врачей",
                        help_text="Добавтье описание ко второй карточке",
                        max_length=300,
                        verbose_name="Описание второй карточки",
                    ),
                ),
                (
                    "button",
                    models.CharField(
                        default="Read more",
                        help_text="Текст на кнопке под второй карточкой",
                        max_length=50,
                        verbose_name="Кнопка номер 2 под карточкой",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Вторая карточка топ блока",
                "verbose_name_plural": "Вторая карточка топ блока",
            },
        ),
        migrations.CreateModel(
            name="ThirdTopCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Поднимите себя до мирового стандарта",
                        help_text="Заголовок терий карточки, по дефолту Поднимите себя до мирового стандарта",
                        max_length=50,
                        verbose_name="Заголовок карточки 3",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Готовьтесь к самому сложному экзамену по медицине в мире чтобы соответствовать высшему уровню профессионализма",
                        help_text="Добавтье описание к третьей карточке",
                        max_length=300,
                        verbose_name="Описание третьей карточки",
                    ),
                ),
                (
                    "button",
                    models.CharField(
                        default="Read more",
                        help_text="Текст на кнопке под третьей карточкой",
                        max_length=50,
                        verbose_name="Кнопка номер 3 под карточкой",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Третья карточка топ блока",
                "verbose_name_plural": "Третья карточка топ блока",
            },
        ),
    ]
