# Generated by Django 4.2.5 on 2023-09-28 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0006_secondtopcard_thirdtopcard"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreBoardMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Subtitle",
                    models.CharField(
                        default="Let me Explain it",
                        help_text="Маленький заголовок над основным заголовком",
                        max_length=100,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Растите с нами",
                        help_text="Основной заголовок",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "colOneNum",
                    models.IntegerField(
                        default="150",
                        help_text="Первый блок, Целое число, максимум 5 знаков",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999),
                        ],
                        verbose_name="Первое число",
                    ),
                ),
                (
                    "colOneText",
                    models.CharField(
                        default="Довольных учеников",
                        help_text="Текст в первой колонке под числом, макимум 50 символов",
                        max_length=50,
                        verbose_name="Первый текст",
                    ),
                ),
                (
                    "colTwoNum",
                    models.IntegerField(
                        default="219",
                        help_text="Второй блок, Целое число, максимум 5 знаков",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999),
                        ],
                        verbose_name="Второе число",
                    ),
                ),
                (
                    "colTwoText",
                    models.CharField(
                        default="Готовятся вместе",
                        help_text="Текст во второй колонке под числом, макимум 50 символов",
                        max_length=50,
                        verbose_name="Второй текст",
                    ),
                ),
                (
                    "colThreeNum",
                    models.IntegerField(
                        default="27",
                        help_text="Третий блок, Целое число, максимум 5 знаков",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999),
                        ],
                        verbose_name="Третье число",
                    ),
                ),
                (
                    "colThreeText",
                    models.CharField(
                        default="Сдавших с нами",
                        help_text="Текст в третьей колонке под числом, макимум 50 символов",
                        max_length=50,
                        verbose_name="Третий текст",
                    ),
                ),
                (
                    "colFourNum",
                    models.IntegerField(
                        default="4",
                        help_text="Четвертый блок, Целое число, максимум 5 знаков",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999),
                        ],
                        verbose_name="Четвертое число",
                    ),
                ),
                (
                    "colFourText",
                    models.CharField(
                        default="На данный момент резидента США",
                        help_text="Текст в четвертой колонке под числом, макимум 50 символов",
                        max_length=50,
                        verbose_name="Четвертый текст",
                    ),
                ),
            ],
            options={
                "verbose_name": "Панель с цифрами",
                "verbose_name_plural": "Панель с цифрами",
            },
        ),
    ]
