# Generated by Django 4.2.5 on 2023-09-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0008_scoreboardmain_created_scoreboardmain_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Наши менторы",
                        help_text="Заголовок блока менторы",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Заголовок Менторы",
                "verbose_name_plural": "Заголовок Менторы",
            },
        ),
        migrations.RemoveField(
            model_name="scoreboardmain",
            name="Subtitle",
        ),
        migrations.AddField(
            model_name="scoreboardmain",
            name="subtitle",
            field=models.CharField(
                default="Let me Explain it",
                help_text="Маленький заголовок над основным заголовком",
                max_length=100,
                verbose_name="Подзаголовок",
            ),
        ),
    ]
