# Generated by Django 4.2.5 on 2023-09-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0009_mentortitle_remove_scoreboardmain_subtitle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Фотография ментора в первой карточке",
                        upload_to="firstMentor/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Курсы",
                        help_text="Подзаголовок над именем и фамилией",
                        max_length=50,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "firstName",
                    models.CharField(
                        default="Аман",
                        help_text="Поле для ввода имени",
                        max_length=50,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "secondName",
                    models.CharField(
                        default="Базаров",
                        help_text="Поле для ввода ффамилии",
                        max_length=50,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        default="USMLE Step 1, Step 2",
                        help_text="Указывается ученая степень",
                        max_length=50,
                        verbose_name="Ученая степень",
                    ),
                ),
                (
                    "exp",
                    models.CharField(
                        default="стажировка США, Окончил с красным дипломом",
                        help_text="Указывается опыт",
                        max_length=50,
                        verbose_name="Опыт",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Первый ментор",
                "verbose_name_plural": "Первый ментор",
            },
        ),
    ]
