# Generated by Django 4.2.5 on 2023-09-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0011_mentortwo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceTitile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Оффлайн/Онлайн",
                        help_text="Маленький заголовок над основным заголовком",
                        max_length=50,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Опции курсов",
                        help_text="Основной заголовок",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Заголовок цены курсы",
                "verbose_name_plural": "Заголовки цен курсов",
            },
        ),
    ]
