# Generated by Django 4.2.5 on 2023-09-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0012_pricetitile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceCardOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upperButton",
                    models.CharField(
                        default="Популярный",
                        help_text="Маленький заголовок над основной карточкой в синем поле",
                        max_length=50,
                        verbose_name="Верхний подзаголовок",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        default="4.5к сом/ мес.",
                        help_text="Цена и срок выделенные зеленым цветом",
                        max_length=50,
                        verbose_name="Цена и срок",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="Подходит для всех желающих обучаться в большом потоке, особенно для студентов.",
                        help_text="Описание над основным заголовком красного цвета",
                        max_length=150,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Standard",
                        help_text="Основной заголовок красного цвета",
                        max_length=50,
                        verbose_name="Основной заголовок",
                    ),
                ),
                (
                    "button",
                    models.CharField(
                        default="Buy Now",
                        help_text="Текст на синей кнопке",
                        max_length=50,
                        verbose_name="Текст на кнопке",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Карточка обучения номер один",
                "verbose_name_plural": "Карточка обучения номер один",
            },
        ),
    ]
