# Generated by Django 4.2.5 on 2023-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0013_pricecardone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceCardOneOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.CharField(
                        help_text="Опция в первой карточке обучения",
                        max_length=50,
                        verbose_name="Опция",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Опция обучения номер один",
                "verbose_name_plural": "Опции обучения номер один",
            },
        ),
    ]
