# Generated by Django 4.2.5 on 2023-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0014_pricecardoneoption"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceCardTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "upperButton",
                    models.CharField(
                        default="Быстрый",
                        help_text="Маленький заголовок над основной карточкой в синем поле",
                        max_length=50,
                        verbose_name="Верхний подзаголовок",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        default="9.8к сом/мес",
                        help_text="Цена и срок выделенные зеленым цветом",
                        max_length=50,
                        verbose_name="Цена и срок",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="Только ординаторы, врачи и студенты 6 курса",
                        help_text="Описание над основным заголовком красного цвета",
                        max_length=150,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Iad`s Method",
                        help_text="Основной заголовок красного цвета",
                        max_length=50,
                        verbose_name="Основной заголовок",
                    ),
                ),
                (
                    "button",
                    models.CharField(
                        default="Buy Now",
                        help_text="Текст на синей кнопке",
                        max_length=50,
                        verbose_name="Текст на кнопке",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка обучения номер один",
                "verbose_name_plural": "Карточка обучения номер один",
            },
        ),
        migrations.CreateModel(
            name="PriceCardTwoOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "option",
                    models.CharField(
                        help_text="Опция во второй карточке обучения",
                        max_length=50,
                        verbose_name="Опция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция обучения номер два",
                "verbose_name_plural": "Опции обучения номер два",
            },
        ),
    ]
