# Generated by Django 4.2.5 on 2023-09-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0015_pricecardtwo_pricecardtwooption"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceCardThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.CharField(
                        default="4к сом/мес или 15к сом за 8 месяцев",
                        help_text="Цена и срок выделенные зеленым цветом",
                        max_length=50,
                        verbose_name="Цена и срок",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="Для тех кто не может найти время, а на курсы так хочется.",
                        help_text="Описание над основным заголовком красного цвета",
                        max_length=150,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Онлайн",
                        help_text="Основной заголовок красного цвета",
                        max_length=50,
                        verbose_name="Основной заголовок",
                    ),
                ),
                (
                    "button",
                    models.CharField(
                        default="Buy Now",
                        help_text="Текст на синей кнопке",
                        max_length=50,
                        verbose_name="Текст на кнопке",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка обучения номер три",
                "verbose_name_plural": "Карточка обучения номер три",
            },
        ),
        migrations.CreateModel(
            name="PriceCardThreeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "option",
                    models.CharField(
                        help_text="Опция во третей карточке обучения",
                        max_length=50,
                        verbose_name="Опция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция обучения номер три",
                "verbose_name_plural": "Опции обучения номер три",
            },
        ),
        migrations.AlterModelOptions(
            name="pricecardtwo",
            options={
                "verbose_name": "Карточка обучения номер два",
                "verbose_name_plural": "Карточка обучения номер два",
            },
        ),
    ]
