# Generated by Django 4.2.5 on 2023-09-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0016_pricecardthree_pricecardthreeoption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DarkBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "subtitle",
                    models.CharField(
                        default="Why not",
                        help_text="Правый подзаголовок на тёмном блоке над основым заголовком блока",
                        max_length=50,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Choose the Best",
                        help_text="Правый заголовок на тёмном блоке ",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "descrition",
                    models.CharField(
                        default="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.",
                        help_text="Опасание под основным заголовком на тёмном блоке ",
                        max_length=200,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "secondTitle",
                    models.CharField(
                        default="Try our freemium theme",
                        help_text="Второй заголовок на светлом блоке",
                        max_length=100,
                        verbose_name="Второй заголовок",
                    ),
                ),
                (
                    "secondDescription",
                    models.CharField(
                        default="With advanced features of higher quality than other similar marketplace themes.",
                        help_text="Опасание под вторым заголоком на светлом блоке ",
                        max_length=200,
                        verbose_name="Второе описание",
                    ),
                ),
                (
                    "button",
                    models.CharField(
                        default="GET STARTED",
                        help_text="Текст на синий кнопке на светлом блоке",
                        max_length=50,
                        verbose_name="Текст на кнопке",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок информации на темном фоне",
                "verbose_name_plural": "Блоки информации на темном фоне",
            },
        ),
    ]
