# Generated by Django 4.2.5 on 2023-09-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0017_darkblock"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "subtitle",
                    models.CharField(
                        default="Помощь от",
                        help_text="Подзаголовок на над основным заголовком",
                        max_length=50,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="В благодраность",
                        help_text="Основной заголовок ",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "imageOne",
                    models.ImageField(
                        help_text="Верхнее фото блока с благодарностями",
                        upload_to="helpone/",
                        verbose_name="Первое фото",
                    ),
                ),
                (
                    "imageTwo",
                    models.ImageField(
                        help_text="Нижнее фото блока с благодарностями",
                        upload_to="helptwo/",
                        verbose_name="Второе фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок благодарностей",
                "verbose_name_plural": "Блоки благодарностей",
            },
        ),
    ]
