# Generated by Django 4.2.5 on 2023-09-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0018_helpblock"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkOptionBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "optionOne",
                    models.CharField(
                        help_text="Ссылки под первым заголовком",
                        max_length=100,
                        verbose_name="Ссылки блок 1",
                    ),
                ),
                (
                    "optionTwo",
                    models.CharField(
                        help_text="Ссылки под вторым заголовком",
                        max_length=100,
                        verbose_name="Ссылки блок 2",
                    ),
                ),
                (
                    "optionThree",
                    models.CharField(
                        help_text="Ссылки под третьем заголовком",
                        max_length=100,
                        verbose_name="Ссылки блок 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылки под заголовком в блоке ссылок",
                "verbose_name_plural": "Ссылки под заголовком в блоке ссылок",
            },
        ),
        migrations.CreateModel(
            name="LinkTitleBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "titleOne",
                    models.CharField(
                        default="Pages",
                        help_text="Первый заголовок",
                        max_length=100,
                        verbose_name="Первый заголовок",
                    ),
                ),
                (
                    "titleTwo",
                    models.CharField(
                        default="Blog",
                        help_text="Второй заголовок",
                        max_length=100,
                        verbose_name="Второй заголовок",
                    ),
                ),
                (
                    "titleThree",
                    models.CharField(
                        default="Contact",
                        help_text="Третий заголовок",
                        max_length=100,
                        verbose_name="Третий заголовок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Названия в блоке ссылок",
                "verbose_name_plural": "Названия в блоке ссылок",
            },
        ),
    ]
