# Generated by Django 4.2.5 on 2023-09-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0019_linkoptionblock_linktitleblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkoptionblock",
            name="optionOne",
            field=models.CharField(
                blank=True,
                help_text="Ссылки под первым заголовком",
                max_length=100,
                verbose_name="Ссылки блок 1",
            ),
        ),
        migrations.AlterField(
            model_name="linkoptionblock",
            name="optionThree",
            field=models.CharField(
                blank=True,
                help_text="Ссылки под третьем заголовком",
                max_length=100,
                verbose_name="Ссылки блок 3",
            ),
        ),
        migrations.AlterField(
            model_name="linkoptionblock",
            name="optionTwo",
            field=models.CharField(
                blank=True,
                help_text="Ссылки под вторым заголовком",
                max_length=100,
                verbose_name="Ссылки блок 2",
            ),
        ),
    ]
